FROM golang:1.25-alpine

WORKDIR /app

RUN apk add --no-cache git curl bash build-base

# Install Air (hot reload)
RUN curl -sSfL https://raw.githubusercontent.com/air-verse/air/master/install.sh | bash -s -- -b /usr/local/bin

COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD ["air", "-c", ".air.toml"]
